### ISSUE TITLE
Gallery fancybox doesn't work

### ISSUE THREAD

**Issue by gavg712** [statnmap/hugo-statnmap-theme#4]
Dear Sebastien, 

I am trying to mount a small blog in GitLab, using your theme and blogdown.  I found the gallery doesn't work properly. The images are overlapped and without any interaction, except open the link. Perhaps the fancybox module is not loading when is called

```
    {{</* gallery
        "/banners/placeholder.png"
        "/banners/placeholder.png"
        "/banners/placeholder.png"
    */>}}
```
I checked the `style.css` file but there is not a class related to fancybox. There is something to do, to run properly the gallery?

**Comment by statnmap** [comment]
Hi,
I never used fancybox, so maybe something is broken.  

I can see that it is loaded in the footer: 
https://github.com/statnmap/hugo-statnmap-theme/blob/b8c7b6fbee18610959c92892fe8e9f2a44bf0a52/layouts/partials/footer_js.html#L1

and that functions and css are here: 
https://github.com/statnmap/hugo-statnmap-theme/tree/master/static/fancybox

But I cannot tell why it is not working correctly for now.
